USE [master]
GO
/****** Object:  Database [WPFCrud]    Script Date: 6/07/2021 23:34:51 ******/
CREATE DATABASE [WPFCrud]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WPFCrud', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\WPFCrud.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WPFCrud_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\WPFCrud_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [WPFCrud] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WPFCrud].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WPFCrud] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WPFCrud] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WPFCrud] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WPFCrud] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WPFCrud] SET ARITHABORT OFF 
GO
ALTER DATABASE [WPFCrud] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WPFCrud] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WPFCrud] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WPFCrud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WPFCrud] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WPFCrud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WPFCrud] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WPFCrud] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WPFCrud] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WPFCrud] SET  DISABLE_BROKER 
GO
ALTER DATABASE [WPFCrud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WPFCrud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WPFCrud] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WPFCrud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WPFCrud] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WPFCrud] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WPFCrud] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WPFCrud] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [WPFCrud] SET  MULTI_USER 
GO
ALTER DATABASE [WPFCrud] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WPFCrud] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WPFCrud] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WPFCrud] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WPFCrud] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [WPFCrud] SET QUERY_STORE = OFF
GO
USE [WPFCrud]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [WPFCrud]
GO
/****** Object:  Table [dbo].[person]    Script Date: 6/07/2021 23:34:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[person](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Age] [int] NULL,
 CONSTRAINT [PK_person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [WPFCrud] SET  READ_WRITE 
GO
